# What We Can Do

We can get 4 year of financial data cleanly outputted

Link: https://towardsdatascience.com/web-scraping-for-accounting-analysis-using-python-part-1-b5fc016a1c9a


Goal is to be able to quickly analyze data to narrowdown investment opportunities

In [86]:
import pandas as pd
from bs4 import BeautifulSoup
import urllib.request as ur

In [87]:
# Enter a stock symbol
index= "FB"
# URL link 
url_is = "https://finance.yahoo.com/quote/" + index + "/financials?p=" + index
url_bs = "https://finance.yahoo.com/quote/" + index +"/balance-sheet?p=" + index
url_cf = "https://finance.yahoo.com/quote/" + index + "/cash-flow?p="+ index

In [88]:
read_data = ur.urlopen(url_bs).read() 
soup_is= BeautifulSoup(read_data,"lxml")

In [89]:
ls= [] # Create empty list
for l in soup_is.find_all("div"): 
  #Find all data structure that is ‘div’
  ls.append(l.string) # add each element one by one to the list

In [90]:
new_ls = list(filter(None,ls))

In [91]:
# don't run more than once on it's own
new_ls = new_ls[12:]
new_ls

['Quarterly',
 '12/31/2019',
 '12/31/2018',
 '12/31/2017',
 '12/31/2016',
 'Cash And Cash Equivalents',
 '19,079,000',
 '10,019,000',
 '8,079,000',
 '8,903,000',
 'Other Short Term Investments',
 '35,776,000',
 '31,095,000',
 '33,632,000',
 '20,546,000',
 'Total Cash',
 '54,855,000',
 '41,114,000',
 '41,711,000',
 '29,449,000',
 'Net Receivables',
 '9,518,000',
 '7,587,000',
 '5,832,000',
 '3,993,000',
 'Total Current Assets',
 '66,225,000',
 '50,480,000',
 '48,563,000',
 '34,401,000',
 'Gross property, plant and equipment',
 '55,446,000',
 '31,573,000',
 '18,337,000',
 '11,803,000',
 'Accumulated Depreciation',
 '-10,663,000',
 '-6,890,000',
 '-4,616,000',
 '-3,212,000',
 'Net property, plant and equipment',
 '44,783,000',
 '24,683,000',
 '13,721,000',
 '8,591,000',
 'Goodwill',
 '18,715,000',
 '18,301,000',
 '18,221,000',
 '18,122,000',
 'Intangible Assets',
 '894,000',
 '1,294,000',
 '1,884,000',
 '2,535,000',
 'Other long-term assets',
 '2,759,000',
 '2,576,000',
 '2,135,000',
 '1,312,000',
 'Total non-current assets',
 '67,151,000',
 '46,854,000',
 '35,961,000',
 '30,560,000',
 'Total Assets',
 '133,376,000',
 '97,334,000',
 '84,524,000',
 '64,961,000',
 'Current Debt',
 '277,000',
 '500,000',
 '-',
 '-',
 'Accounts Payable',
 '1,363,000',
 '820,000',
 '380,000',
 '302,000',
 'Accrued liabilities',
 '6,632,000',
 '1,531,000',
 '685,000',
 '331,000',
 'Deferred revenues',
 '269,000',
 '147,000',
 '98,000',
 '90,000',
 'Other Current Liabilities',
 '2,498,000',
 '1,784,000',
 '1,201,000',
 '1,236,000',
 'Total Current Liabilities',
 '15,053,000',
 '7,017,000',
 '3,760,000',
 '2,875,000',
 'Deferred taxes liabilities',
 '1,039,000',
 '673,000',
 '-',
 '-',
 'Other long-term liabilities',
 '1,055,000',
 '862,000',
 '1,045,000',
 '461,000',
 'Total non-current liabilities',
 '17,269,000',
 '6,190,000',
 '6,417,000',
 '2,892,000',
 'Total Liabilities',
 '32,322,000',
 '13,207,000',
 '10,177,000',
 '5,767,000',
 'Common Stock',
 '0',
 '0',
 '0',
 '0',
 'Retained Earnings',
 '55,692,000',
 '41,981,000',
 '33,990,000',
 '21,670,000',
 'Accumulated other comprehensive income',
 '-489,000',
 '-760,000',
 '-227,000',
 '-703,000',
 "Total stockholders' equity",
 '101,054,000',
 '84,127,000',
 '74,347,000',
 '59,194,000',
 "Total liabilities and stockholders' equity",
 '133,376,000',
 '97,334,000',
 '84,524,000',
 '64,961,000',
 'Learn more',
 '© 2020 Verizon Media. All rights reserved.']

In [92]:
# essentially how many the columns, *x as the delimeter
is_data = list(zip(*[iter(new_ls)]*5))

In [93]:
Income_st = pd.DataFrame(is_data[0:])
Income_st

,0,1,2,3,4
0,Quarterly,12/31/2019,12/31/2018,12/31/2017,12/31/2016
1,Cash And Cash Equivalents,"19,079,000","10,019,000","8,079,000","8,903,000"
2,Other Short Term Investments,"35,776,000","31,095,000","33,632,000","20,546,000"
3,Total Cash,"54,855,000","41,114,000","41,711,000","29,449,000"
4,Net Receivables,"9,518,000","7,587,000","5,832,000","3,993,000"
5,Total Current Assets,"66,225,000","50,480,000","48,563,000","34,401,000"
6,"Gross property, plant and equipment","55,446,000","31,573,000","18,337,000","11,803,000"
7,Accumulated Depreciation,"-10,663,000","-6,890,000","-4,616,000","-3,212,000"
8,"Net property, plant and equipment","44,783,000","24,683,000","13,721,000","8,591,000"
9,Goodwill,"18,715,000","18,301,000","18,221,000","18,122,000"
10,Intangible Assets,"894,000","1,294,000","1,884,000","2,535,000"
11,Other long-term assets,"2,759,000","2,576,000","2,135,000","1,312,000"
12,Total non-current assets,"67,151,000","46,854,000","35,961,000","30,560,000"
13,Total Assets,"133,376,000","97,334,000","84,524,000","64,961,000"
14,Current Debt,"277,000","500,000",-,-
15,Accounts Payable,"1,363,000","820,000","380,000","302,000"
16,Accrued liabilities,"6,632,000","1,531,000","685,000","331,000"
17,Deferred revenues,"269,000","147,000","98,000","90,000"
18,Other Current Liabilities,"2,498,000","1,784,000","1,201,000","1,236,000"
19,Total Current Liabilities,"15,053,000","7,017,000","3,760,000","2,875,000"
20,Deferred taxes liabilities,"1,039,000","673,000",-,-
21,Other long-term liabilities,"1,055,000","862,000","1,045,000","461,000"
22,Total non-current liabilities,"17,269,000","6,190,000","6,417,000","2,892,000"
23,Total Liabilities,"32,322,000","13,207,000","10,177,000","5,767,000"
24,Common Stock,0,0,0,0
25,Retained Earnings,"55,692,000","41,981,000","33,990,000","21,670,000"
26,Accumulated other comprehensive income,"-489,000","-760,000","-227,000","-703,000"
27,Total stockholders' equity,"101,054,000","84,127,000","74,347,000","59,194,000"
28,Total liabilities and stockholders' equity,"133,376,000","97,334,000","84,524,000","64,961,000"

In [94]:
Income_st.columns = Income_st.iloc[0] # Name columns to first row of dataframe
Income_st = Income_st.iloc[1:,] # start to read 1st row
Income_st = Income_st.T # transpose dataframe
Income_st.columns = Income_st.iloc[0] #Name columns to first row of dataframe
Income_st.drop(Income_st.index[0],inplace=True) #Drop first index row
Income_st.index.name = "" # Remove the index name
Income_st.rename(index={"ttm": "12/31/2019"},inplace=True) #Rename ttm in index columns to end of the year
Income_st = Income_st[Income_st.columns[:-5]] # remove last 5 irrelevant columns

In [95]:
Income_st

Quarterly,Cash And Cash Equivalents,Other Short Term Investments,Total Cash,Net Receivables,Total Current Assets,"Gross property, plant and equipment",Accumulated Depreciation,"Net property, plant and equipment",Goodwill,Intangible Assets,...,Current Debt,Accounts Payable,Accrued liabilities,Deferred revenues,Other Current Liabilities,Total Current Liabilities,Deferred taxes liabilities,Other long-term liabilities,Total non-current liabilities,Total Liabilities
,,,,,,,,,,,,,,,,,,,,,
12/31/2019,"19,079,000","35,776,000","54,855,000","9,518,000","66,225,000","55,446,000","-10,663,000","44,783,000","18,715,000","894,000",...,"277,000","1,363,000","6,632,000","269,000","2,498,000","15,053,000","1,039,000","1,055,000","17,269,000","32,322,000"
12/31/2018,"10,019,000","31,095,000","41,114,000","7,587,000","50,480,000","31,573,000","-6,890,000","24,683,000","18,301,000","1,294,000",...,"500,000","820,000","1,531,000","147,000","1,784,000","7,017,000","673,000","862,000","6,190,000","13,207,000"
12/31/2017,"8,079,000","33,632,000","41,711,000","5,832,000","48,563,000","18,337,000","-4,616,000","13,721,000","18,221,000","1,884,000",...,-,"380,000","685,000","98,000","1,201,000","3,760,000",-,"1,045,000","6,417,000","10,177,000"
12/31/2016,"8,903,000","20,546,000","29,449,000","3,993,000","34,401,000","11,803,000","-3,212,000","8,591,000","18,122,000","2,535,000",...,-,"302,000","331,000","90,000","1,236,000","2,875,000",-,"461,000","2,892,000","5,767,000"

In [96]:
finalIS = Income_st[0:5]

In [97]:
finalIS

Quarterly,Cash And Cash Equivalents,Other Short Term Investments,Total Cash,Net Receivables,Total Current Assets,"Gross property, plant and equipment",Accumulated Depreciation,"Net property, plant and equipment",Goodwill,Intangible Assets,...,Current Debt,Accounts Payable,Accrued liabilities,Deferred revenues,Other Current Liabilities,Total Current Liabilities,Deferred taxes liabilities,Other long-term liabilities,Total non-current liabilities,Total Liabilities
,,,,,,,,,,,,,,,,,,,,,
12/31/2019,"19,079,000","35,776,000","54,855,000","9,518,000","66,225,000","55,446,000","-10,663,000","44,783,000","18,715,000","894,000",...,"277,000","1,363,000","6,632,000","269,000","2,498,000","15,053,000","1,039,000","1,055,000","17,269,000","32,322,000"
12/31/2018,"10,019,000","31,095,000","41,114,000","7,587,000","50,480,000","31,573,000","-6,890,000","24,683,000","18,301,000","1,294,000",...,"500,000","820,000","1,531,000","147,000","1,784,000","7,017,000","673,000","862,000","6,190,000","13,207,000"
12/31/2017,"8,079,000","33,632,000","41,711,000","5,832,000","48,563,000","18,337,000","-4,616,000","13,721,000","18,221,000","1,884,000",...,-,"380,000","685,000","98,000","1,201,000","3,760,000",-,"1,045,000","6,417,000","10,177,000"
12/31/2016,"8,903,000","20,546,000","29,449,000","3,993,000","34,401,000","11,803,000","-3,212,000","8,591,000","18,122,000","2,535,000",...,-,"302,000","331,000","90,000","1,236,000","2,875,000",-,"461,000","2,892,000","5,767,000"

## Financial Statement Analysis
Income Statement: Look for increasing operating income, % of revenue increase

Statement of Cash Flow: We need to be able to automatically change into the summary analysis and make judgments

Balance Sheet: Just look at key accounts, and calculate that ratio you did in Grubhub Project (Z-ratio)

In [98]:
isAnalysis = finalIS

In [99]:
# Use iloc in this particular analysis, or loc if you can for the specific names

isAnalysis.iloc[0:3, 0:4]

Quarterly,Cash And Cash Equivalents,Other Short Term Investments,Total Cash,Net Receivables
,,,,
12/31/2019,"19,079,000","35,776,000","54,855,000","9,518,000"
12/31/2018,"10,019,000","31,095,000","41,114,000","7,587,000"
12/31/2017,"8,079,000","33,632,000","41,711,000","5,832,000"