# Scraping data using yfinance

https://aroussi.com/post/python-yahoo-finance

https://github.com/ranaroussi/yfinance/blob/master/README.rst

In [8]:
pip install yfinance

Requirement already satisfied: yfinance in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (0.1.54)
Requirement already satisfied: numpy>=1.15 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from yfinance) (1.16.4)
Requirement already satisfied: multitasking>=0.0.7 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from yfinance) (0.0.9)
Requirement already satisfied: requests>=2.20 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from yfinance) (2.22.0)
Requirement already satisfied: pandas>=0.24 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from yfinance) (0.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2.8)
Requirement already satisfied: python-dateutil>=2.5.0 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2.8.0)
Requirement already satisfied: pytz>=2011k in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2019.1)
Requirement already satisfied: six>=1.5 in /Users/anthonylin/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas>=0.24->yfinance) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import yfinance as yf

In [10]:
msft = yf.Ticker("FB")
msft.earnings

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [11]:
# Getting stock prices
data = yf.download("FB", start="2020-01-01", end="2020-4-30",
                   group_by="ticker")

[*********************100%***********************]  1 of 1 completed

In [12]:
data.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-01-02,206.750000,209.789993,206.270004,209.779999,209.779999,12077100
2020-01-03,207.210007,210.399994,206.949997,208.669998,208.669998,11188400
2020-01-06,206.699997,212.779999,206.520004,212.600006,212.600006,17058900
2020-01-07,212.820007,214.580002,211.750000,213.059998,213.059998,14912400
2020-01-08,213.000000,216.240005,212.610001,215.220001,215.220001,13475000

# Accessing Elements in Dataframe
https://pythonhow.com/accessing-dataframe-columns-rows-and-cells/

In [13]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-01-02,206.750000,209.789993,206.270004,209.779999,209.779999,12077100
2020-01-03,207.210007,210.399994,206.949997,208.669998,208.669998,11188400
2020-01-06,206.699997,212.779999,206.520004,212.600006,212.600006,17058900
2020-01-07,212.820007,214.580002,211.750000,213.059998,213.059998,14912400
2020-01-08,213.000000,216.240005,212.610001,215.220001,215.220001,13475000
2020-01-09,217.539993,218.380005,216.279999,218.300003,218.300003,12642800
2020-01-10,219.199997,219.880005,217.419998,218.059998,218.059998,12119400
2020-01-13,219.600006,221.970001,219.210007,221.910004,221.910004,14463400
2020-01-14,221.610001,222.380005,218.630005,219.059998,219.059998,13288900
2020-01-15,220.610001,221.679993,220.139999,221.149994,221.149994,10036500
2020-01-16,222.570007,222.630005,220.389999,221.770004,221.770004,10015300
2020-01-17,222.029999,222.289993,220.529999,222.139999,222.139999,15905900
2020-01-21,222.160004,222.369995,219.119995,221.440002,221.440002,14275800
2020-01-22,222.309998,222.750000,221.279999,221.320007,221.320007,12212800
2020-01-23,220.750000,221.490005,219.270004,219.759995,219.759995,11195000
2020-01-24,220.800003,221.779999,216.110001,217.940002,217.940002,11905800
2020-01-27,213.100006,216.059998,212.500000,214.869995,214.869995,13810700
2020-01-28,216.139999,218.740005,213.520004,217.789993,217.789993,13413800
2020-01-29,221.440002,224.199997,218.449997,223.229996,223.229996,33181300
2020-01-30,206.529999,211.429993,204.750000,209.529999,209.529999,48775500
2020-01-31,208.429993,208.690002,201.059998,201.910004,201.910004,31359900
2020-02-03,203.440002,205.139999,202.500000,204.190002,204.190002,15510500
2020-02-04,206.619995,210.600006,205.199997,209.830002,209.830002,19628900
2020-02-05,212.509995,212.729996,208.710007,210.110001,210.110001,12538200
2020-02-06,210.470001,211.190002,209.339996,210.850006,210.850006,10567500
2020-02-07,210.300003,212.820007,209.929993,212.330002,212.330002,12242500
2020-02-10,211.520004,213.800003,210.660004,213.059998,213.059998,11856400
2020-02-11,210.190002,210.860001,206.509995,207.190002,207.190002,25030800
2020-02-12,207.850006,211.220001,207.399994,210.759995,210.759995,13813700
2020-02-13,209.520004,214.330002,209.179993,213.139999,213.139999,15396600
...,...,...,...,...,...,...
2020-03-18,139.750000,148.179993,137.100006,146.960007,146.960007,37553100
2020-03-19,146.619995,159.929993,144.800003,153.130005,153.130005,39862300
2020-03-20,156.020004,159.270004,148.000000,149.729996,149.729996,32568400
2020-03-23,149.660004,152.309998,142.250000,148.100006,148.100006,29830800
2020-03-24,155.210007,161.309998,152.570007,160.979996,160.979996,30440400
2020-03-25,158.919998,162.990005,153.059998,156.210007,156.210007,35184300
2020-03-26,158.250000,164.000000,157.020004,163.339996,163.339996,26556800
2020-03-27,158.199997,160.089996,154.750000,156.789993,156.789993,24879900
2020-03-30,159.179993,166.750000,158.059998,165.949997,165.949997,22515200
2020-03-31,165.479996,170.929993,164.199997,166.800003,166.800003,23676300
2020-04-01,161.619995,164.149994,158.039993,159.600006,159.600006,19507600
2020-04-02,159.100006,161.350006,155.919998,158.190002,158.190002,20886300
2020-04-03,157.149994,157.910004,150.830002,154.179993,154.179993,25983300
2020-04-06,160.149994,166.199997,158.509995,165.550003,165.550003,28453600
2020-04-07,171.789993,173.389999,166.009995,168.830002,168.830002,31411900
2020-04-08,171.250000,175.000000,167.740005,174.279999,174.279999,21664200
2020-04-09,175.899994,177.080002,171.570007,175.190002,175.190002,23534300
2020-04-13,173.669998,175.000000,169.449997,174.789993,174.789993,19355400
2020-04-14,178.979996,181.229996,176.619995,178.169998,178.169998,21011800
2020-04-15,175.190002,178.190002,172.820007,176.970001,176.970001,17423000
2020-04-16,177.949997,178.050003,172.509995,176.250000,176.250000,23593200
2020-04-17,179.199997,180.279999,176.660004,179.240005,179.240005,20974800
2020-04-20,177.410004,180.500000,176.770004,178.240005,178.240005,16110700
2020-04-21,175.250000,175.380005,168.339996,170.800003,170.800003,24850500
2020-04-22,178.449997,184.779999,178.139999,182.279999,182.279999,33369900
2020-04-23,184.080002,187.050003,183.149994,185.130005,185.130005,21426600
2020-04-24,183.229996,190.410004,180.830002,190.070007,190.070007,28868500
2020-04-27,192.660004,193.750000,187.410004,187.500000,187.500000,29197800
2020-04-28,188.660004,189.199997,182.559998,182.910004,182.910004,21731000
2020-04-29,190.929993,196.910004,190.000000,194.190002,194.190002,45954500

In [14]:
simplifiedData = data

simplifiedData = simplifiedData.drop("High", axis=1)
simplifiedData = simplifiedData.drop("Low", axis=1)


simplifiedData

                  Open       Close   Adj Close    Volume
Date
2020-01-02  206.750000  209.779999  209.779999  12077100
2020-01-03  207.210007  208.669998  208.669998  11188400
2020-01-06  206.699997  212.600006  212.600006  17058900
2020-01-07  212.820007  213.059998  213.059998  14912400
2020-01-08  213.000000  215.220001  215.220001  13475000
2020-01-09  217.539993  218.300003  218.300003  12642800
2020-01-10  219.199997  218.059998  218.059998  12119400
2020-01-13  219.600006  221.910004  221.910004  14463400
2020-01-14  221.610001  219.059998  219.059998  13288900
2020-01-15  220.610001  221.149994  221.149994  10036500
2020-01-16  222.570007  221.770004  221.770004  10015300
2020-01-17  222.029999  222.139999  222.139999  15905900
2020-01-21  222.160004  221.440002  221.440002  14275800
2020-01-22  222.309998  221.320007  221.320007  12212800
2020-01-23  220.750000  219.759995  219.759995  11195000
2020-01-24  220.800003  217.940002  217.940002  11905800
2020-01-27  213.100006  214.869995  214.869995  13810700
2020-01-28  216.139999  217.789993  217.789993  13413800
2020-01-29  221.440002  223.229996  223.229996  33181300
2020-01-30  206.529999  209.529999  209.529999  48775500
2020-01-31  208.429993  201.910004  201.910004  31359900
2020-02-03  203.440002  204.190002  204.190002  15510500
2020-02-04  206.619995  209.830002  209.830002  19628900
2020-02-05  212.509995  210.110001  210.110001  12538200
2020-02-06  210.470001  210.850006  210.850006  10567500
2020-02-07  210.300003  212.330002  212.330002  12242500
2020-02-10  211.520004  213.059998  213.059998  11856400
2020-02-11  210.190002  207.190002  207.190002  25030800
2020-02-12  207.850006  210.759995  210.759995  13813700
2020-02-13  209.520004  213.139999  213.139999  15396600
...                ...         ...         ...       ...
2020-03-18  139.750000  146.960007  146.960007  37553100
2020-03-19  146.619995  153.130005  153.130005  39862300
2020-03-20  156.020004  149.729996  149.729996  32568400
2020-03-23  149.660004  148.100006  148.100006  29830800
2020-03-24  155.210007  160.979996  160.979996  30440400
2020-03-25  158.919998  156.210007  156.210007  35184300
2020-03-26  158.250000  163.339996  163.339996  26556800
2020-03-27  158.199997  156.789993  156.789993  24879900
2020-03-30  159.179993  165.949997  165.949997  22515200
2020-03-31  165.479996  166.800003  166.800003  23676300
2020-04-01  161.619995  159.600006  159.600006  19507600
2020-04-02  159.100006  158.190002  158.190002  20886300
2020-04-03  157.149994  154.179993  154.179993  25983300
2020-04-06  160.149994  165.550003  165.550003  28453600
2020-04-07  171.789993  168.830002  168.830002  31411900
2020-04-08  171.250000  174.279999  174.279999  21664200
2020-04-09  175.899994  175.190002  175.190002  23534300
2020-04-13  173.669998  174.789993  174.789993  19355400
2020-04-14  178.979996  178.169998  178.169998  21011800
2020-04-15  175.190002  176.970001  176.970001  17423000
2020-04-16  177.949997  176.250000  176.250000  23593200
2020-04-17  179.199997  179.240005  179.240005  20974800
2020-04-20  177.410004  178.240005  178.240005  16110700
2020-04-21  175.250000  170.800003  170.800003  24850500
2020-04-22  178.449997  182.279999  182.279999  33369900
2020-04-23  184.080002  185.130005  185.130005  21426600
2020-04-24  183.229996  190.070007  190.070007  28868500
2020-04-27  192.660004  187.500000  187.500000  29197800
2020-04-28  188.660004  182.910004  182.910004  21731000
2020-04-29  190.929993  194.190002  194.190002  45954500

[82 rows x 4 columns]